package com.skytech.crm.enums;

public enum ActivityType {
  UNAUTHORIZED_LOGIN,
  LEAD_STATUS_CHANGED,
  LEAD_LOG_CALL,
  LEAD_STAGE_CHANGED,
  TASK_STATUS_CHANGED,
  COMMENT_RECEIVED_TASK,
  COMMENT_RECEIVED_LEAD,
  SUBTASK_CREATED,
  TASK_APPROVED,
  HOSTING_EXPIRY_NOTICE,
  DOMAIN_EXPIRY_NOTICE,
  MAINTENANCE_EXPIRY_NOTICE
}
